import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { PropsWithChildren } from 'react';
import { Providers } from '@/redux';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cogitize solutions test task by Bohdan Ryzhko',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
